/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passwordgenerator;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author uyat
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        pwdPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generatePwdBtn = new javax.swing.JButton();
        getCredentialBtn = new javax.swing.JButton();
        credPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        envTextField = new javax.swing.JTextField();
        userNameTextField = new javax.swing.JTextField();
        pwdPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pwdTextField = new javax.swing.JTextField();
        closeBtn = new javax.swing.JButton();
        storeBtn = new javax.swing.JButton();
        pwdFormatBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        generatePwdBtn.setText("Generate Password");
        generatePwdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePwdBtnActionPerformed(evt);
            }
        });

        getCredentialBtn.setText("Get stored password");
        getCredentialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getCredentialBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Environment : ");

        jLabel2.setText("Username     :");

        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout credPanelLayout = new javax.swing.GroupLayout(credPanel);
        credPanel.setLayout(credPanelLayout);
        credPanelLayout.setHorizontalGroup(
            credPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(credPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(credPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(credPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(envTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        credPanelLayout.setVerticalGroup(
            credPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(credPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(credPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(envTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(credPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pwdPanel.setBackground(new java.awt.Color(153, 153, 153));

        jLabel3.setText("Password      :");

        pwdTextField.setEditable(false);

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        storeBtn.setText("Store");
        storeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pwdPanelLayout = new javax.swing.GroupLayout(pwdPanel);
        pwdPanel.setLayout(pwdPanelLayout);
        pwdPanelLayout.setHorizontalGroup(
            pwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pwdPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(pwdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pwdPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(storeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeBtn)
                .addGap(41, 41, 41))
        );
        pwdPanelLayout.setVerticalGroup(
            pwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pwdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(pwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storeBtn)
                    .addComponent(closeBtn))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pwdFormatBtn.setText("Change password format");
        pwdFormatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdFormatBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(credPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(generatePwdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(getCredentialBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pwdFormatBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pwdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(credPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(generatePwdBtn)
                .addGap(18, 18, 18)
                .addComponent(getCredentialBtn)
                .addGap(18, 18, 18)
                .addComponent(pwdFormatBtn)
                .addGap(27, 27, 27)
                .addComponent(pwdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generatePwdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePwdBtnActionPerformed
        // TODO add your handling code here:
        //PwdGenerateForm pwdForm = new PwdGenerateForm();
        //pwdForm.setVisible(true);
        getCredentialBtn.setEnabled(false);
        PasswordStorageManager mngr = new PasswordStorageManager();
        String pwdMinLength,pwdMaxLength,pwdNoOfDigits,pwdNoOfCaps,pwdNoOfSpcl;
        if((pwdMinLength = mngr.getConfigValue("MinLength"))==null)
        {
            pwdMinLength = "7";
        }
        if((pwdMaxLength = mngr.getConfigValue("MaxLength")) == null)
        {
            pwdMaxLength = "10";
        }
        if((pwdNoOfDigits = mngr.getConfigValue("NoOfDigits")) == null)
        {
            pwdNoOfDigits = "2";
        }
        if((pwdNoOfCaps = mngr.getConfigValue("NoOfCaps")) ==null)
        {
            pwdNoOfCaps = "2";
        }
        if((pwdNoOfSpcl = mngr.getConfigValue("NoOfSpcl")) == null)
        {
            pwdNoOfSpcl = "2";
        }
        String pwd = PasswordGenerator.generateRandomPass(Integer.parseInt(pwdMinLength),Integer.parseInt(pwdMaxLength),
                             Integer.parseInt(pwdNoOfCaps),Integer.parseInt(pwdNoOfDigits),Integer.parseInt(pwdNoOfSpcl));
        pwdPanel.setVisible(true);
        storeBtn.setVisible(true);
        pwdTextField.setText(pwd);
    }//GEN-LAST:event_generatePwdBtnActionPerformed

    private void getCredentialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getCredentialBtnActionPerformed
        // TODO add your handling code here:
        if(envTextField.getText().equals("") || userNameTextField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Invalid Input","Error",JOptionPane.ERROR_MESSAGE);
        }
        generatePwdBtn.setEnabled(false);
        
        String username = userNameTextField.getText();
        String env = envTextField.getText();
          
        PasswordStorageManager pwdMngr= new PasswordStorageManager();
        String password = pwdMngr.getPassword(username,env);
        if(password == null)
        {
            JOptionPane.showMessageDialog(null, "Password doesn't exist","Error",JOptionPane.ERROR_MESSAGE);
        }else{
          pwdPanel.setVisible(true);
          storeBtn.setVisible(false);
          pwdTextField.setText(password);  
        }
       
           
    }//GEN-LAST:event_getCredentialBtnActionPerformed

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextFieldActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        pwdPanel.setVisible(false);
        generatePwdBtn.setEnabled(true);
        getCredentialBtn.setEnabled(true);
    }//GEN-LAST:event_closeBtnActionPerformed

    private void pwdFormatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdFormatBtnActionPerformed
        // TODO add your handling code here:
      PwdConfigureForm confForm = new PwdConfigureForm();
      confForm.setVisible(true);
    }//GEN-LAST:event_pwdFormatBtnActionPerformed

    private void storeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeBtnActionPerformed
        // TODO add your handling code here:
        generatePwdBtn.setEnabled(true);
        String username,env,pwd;
        if(userNameTextField.getText().equals("") || envTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Invalid Input","Error",JOptionPane.ERROR_MESSAGE);
        }else
        {
          username = userNameTextField.getText();
          env = envTextField.getText();
          pwd = pwdTextField.getText();
          new PasswordStorageManager().storePassword(username, env, pwd);
        }     
    }//GEN-LAST:event_storeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JPanel credPanel;
    private javax.swing.JTextField envTextField;
    private javax.swing.JButton generatePwdBtn;
    private javax.swing.JButton getCredentialBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton pwdFormatBtn;
    private javax.swing.JPanel pwdPanel;
    private javax.swing.JTextField pwdTextField;
    private javax.swing.JButton storeBtn;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
